package com.itsazni.notificationforwarder.worker
import android.content.Context
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.itsazni.notificationforwarder.data.*
import com.itsazni.notificationforwarder.settings.SettingsStore
class QueueWorker(appContext:Context,params:WorkerParameters):CoroutineWorker(appContext,params){private val repository=NotificationRepository(appContext);private val settings=SettingsStore(appContext);private val processor=QueueItemProcessor(appContext,repository,settings);private val diagnostics=DiagnosticsRepository(appContext)
 override suspend fun doWork():Result{diagnostics.record(DiagnosticEvent(type=DiagnosticEventType.WORKER_STARTED,category=DiagnosticCategory.WORKER,message="Queue worker execution started"));val config=settings.readAll();if(!config.forwardingEnabled||config.webhookUrl.isBlank())return Result.success();repository.recoverStaleSending(STALE_SENDING_MILLIS);val target=inputData.getLong(INPUT_QUEUE_ITEM_ID,NO_ITEM_ID);if(target!=NO_ITEM_ID){val item=repository.getById(target)?:return Result.success();if(item.status!=QueueStatus.PENDING&&item.status!=QueueStatus.FAILED)return Result.success();if(runAttemptCount>0&&item.status==QueueStatus.PENDING&&item.nextRetryAt>System.currentTimeMillis())return Result.retry();val r=processor.process(item,config);return if(r.shouldRetryWorker)Result.retry() else Result.success()};val retryAll=inputData.getBoolean(INPUT_RETRY_ALL,false);var shouldRetry=false;do{val items=repository.getPending(config.batchSize);if(items.isEmpty())break;items.forEach{val r=processor.process(it,config);shouldRetry=shouldRetry||r.shouldRetryWorker}}while(retryAll);return if(shouldRetry)Result.retry() else Result.success()}
 companion object{const val INPUT_QUEUE_ITEM_ID="queue_item_id";const val INPUT_RETRY_ALL="retry_all";const val NO_ITEM_ID=-1L;const val STALE_SENDING_MILLIS=5*60*1000L}}
